config/routes.rb
Tunda::Application.routes.draw do
  get "contact/contact"
  resources :line_items

  resources :carts

  resources :orders

  resources :products

  devise_for :users
  get "pages/home"

  get "pages/about"

  root :to => 'pages#home' , :as => 'home'
end

app/models/product.rb
class Product < ActiveRecord::Base
	#attr_accessible :image
	before_destroy :ensure_not_referenced_by_any_line_item
	has_attached_file :image, :styles => { :medium => "320x240" },
		:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"
	belongs_to :user

	validates :title, :description, :presence => true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	validates :title, :uniqueness => true
	#validates_attachment :image, :presence => true,
	#							:content_type => { :content_type => ['image/jpg', 'image/jpeg','image/gif','image/png',]},
	#							:size => { less_than: 5.megabytes}									
	
	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors.add(:base, 'Line Items present' )
			return false
		end
	end


	belongs_to :user
	#belongs_to :order
	has_many :line_items

									
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user! except: [:index]
  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(:page       => params[:page],
                           :per_page   => 20,
                           :order      => 'created_at ASC')
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @prod = Product.find(params[:id])
 
  end

  # GET /products/new
  def new
    @prod = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @prod.update(product_params)
        format.html { redirect_to @prod, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @prod.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
        begin
          @prod = Product.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          logger.error "Attempt to access invalid cart #{params[:id]}"
          redirect_to products_url, :notice => 'Invalid Product'
        
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@prod, :class => 'form-horizontal') do |f| %>
  <%= f.error_notification %>
   <%= f.full_error :image_file_size, class: "alert alert-error" %>
   <%= f.full_error :image_content_type, class: "alert alert-error" %>

 <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, :as => 'text',:rows => '3', :label => 'Description'  %>
    <%= f.input :image, label: 'Upload an image' %>
    <%= f.input :price %>
</div>
  <div class="form-actions">
    <%= f.button :submit, 'Create Product', :class => 'btn btn-primary'  %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class='box span3'>
				<h4><p><%= product.title %></p></h4>
				<%= link_to image_tag(product.image(:medium)) , product %>
				<%#<%= link_to 'Show' , product, :class => 'btn btn-primary' %>
				<% if current_user != product.user %>
				<p><%= link_to 'Edit' , edit_product_path(product) %> |
				<%= link_to 'Destroy' , product, :method => :delete, data: {:confirm => 'Are you sure?'} %></p>
				
				<% end %>
			</div>
			

app/views/products/edit.html.erb
<legend>Editing product</legend>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id= 'pins'>

	<%= render @products %>
</div>

<div class="pagination pagination-mini pagination-right">
<%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/new.html.erb
<legend><h4>New product</h4></legend>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class='row'>
	<div class='span6 offset3'>
		<div class="well">
        <p>

          <%= @prod.title %>
        </p>

        <p><%= @prod.description %></p>
        
        <p>
            <%= image_tag(@prod.image(:medium), :class => 'list_image' ) %>
        </p>

        <p>

          <%= number_to_currency(@prod.price) %>
        </p>
        
        <p><%= link_to 'Edit', edit_product_path(@prod) %> |
            <%= link_to 'Back', products_path %></p>
        <p>
            
        <%= button_to 'Add to Cart', line_items_path(:product_id => @prod), :class => 'btn btn-primary' %>
    </p>
       
	</div>
	</div>
</div>
    