config/routes.rb
Tunda::Application.routes.draw do
  get "contact/contact"
  resources :line_items

  resources :carts

  resources :orders

  resources :products

  devise_for :users
  get "pages/home"

  get "pages/about"

  root :to => 'pages#home' , :as => 'home'
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		</p>© Tunda Uganda 2014</p>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</a>
				<a class="brand" href="/">Tunda</a>
				<div class="nav-collapse collapse">
				<ul class="nav">
			
					<%#<li class="active"><a href="/" >Home</a></li> %>
					<li class='active'><%= link_to 'Home', products_path %></li>
					

					
			</ul>
			<ul class="nav pull-right">
				<li><%= link_to 'Contact Us', contact_contact_path %></li>
				<% if !user_signed_in? %>
					<li><%= link_to 'Login', new_user_session_path %></li>
					<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				<% else %>
					<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
					<li><%= link_to 'New Product', new_product_path %></li>
					<li><%= link_to 'Check Orders', orders_path %></li>
					<li><%= link_to 'Logout' , destroy_user_session_path, :method => :delete %></li>
				<% end %>

			</ul>

				</div>
				</div>
				</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunda</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<%= render 'layouts/header' %>
			 <div class="container">           
                <% flash.each do |name, msg| %>
                   <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
                   	<% end %>
						<%= yield %>	
			</div>
			<div class="footer">
						<%= render 'layouts/footer' %>
					</div>
			

	</body>
</html>